# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	
	lane :beta do
		build_app(scheme: "DailyCorona", 
							export_xcargs: "-allowProvisioningUpdates")
		upload_to_testflight(changelog: File.read("../what_to_test.txt"),
												 groups: [])
		increment_build_number
		commit_version_bump
		push_to_git_remote
	end

	lane :basic do
		appicon(appicon_image_file: 'fastlane/coronadaily.pdf',
						appicon_devices: [:iphone, :ios_marketing],
						appicon_path: "DailyCorona/Assets.xcassets")
	end

end
